project:
  type: website
  output-dir: docs

website:
  title: "quarto_demo"
  navbar:
    background: primary
    right:
      - href: table.qmd
        text: df_print
      - href: dark_mode.qmd
        text: dark mode

format:
  html:
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    css: styles.css
    comments:
      hypothesis: 
        theme: clean


