project:
  type: website
  output-dir: docs

website:
  title: "quarto_demo"
  navbar:
    background: primary

format:
  html:
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    css: styles.css
    comments:
      hypothesis: 
        theme: clean


