project:
  type: website
  output-dir: docs

website:
  title: "quarto_demo"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: table.qmd
        text: df_print

format:
  html:
    theme: yeti
    css: styles.css



